### ISSUE TITLE
EIOPA changed RFR link

### ISSUE THREAD

**Issue by johalnes** [DeNederlandscheBank/solvency2-data#1]
* solvency2-rfr version: 0.1.5
* Python version: 3.8.1
* Operating System: MacOSX 10.14.6

### Description

EIOPA have changed their websites, and moved all their sites. All google links are broken, and the link given in this package for RFR is also wrong. 

### What I Did

```
import solvency2_data
import datetime as dt

d = solvency2_data.read(dt.datetime(2017,12,31))

>>> 404 Page not found error
```

**Comment by wjwillemse** [comment]
Thanks for solving this johalnes!

**Comment by wjwillemse** [comment]
EIOPA RFRs are archived at a location on their website than the 'current' RFRs. Naming also does not seem to be consistent. I have re-opened this issue.

**Comment by wjwillemse** [comment]
I had some difficulties deploying to pypi, but now it works. Unittests also work again. It seems that there is only one location on EIOPA website where the actual RFRs are located. Only remaining problem is the name of some RFRs: RFR of 20191231 has name eiopa_rfr_20191231_0_0.zip and RFR of 20191130 has name eiopa_rfr_20191130_0.zip. I will take this up with EIOPA.

**Comment by wjwillemse** [comment]
I contacted EIOPA; the 0 added in the name of the files is an error, the 0 was generated automatically when uploading files with the same name. The naming convention will remain as in eiopa_rfr_20200131.zip. So this issue is solved.

**Comment by pdavidsonFIA** [comment]
Regarding this issue, I set up regex matching in scraping.eiopa_link.
Example provided to generate a link for every month for rfr and symmetric adjustment.
